# Generated by Django 4.0.5 on 2022-07-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_pickup_remove_order_product_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pickUp_Date',
        ),
        migrations.AlterField(
            model_name='pickup',
            name='pickup',
            field=models.DateTimeField(null=True, verbose_name='Pickup Date'),
        ),
    ]
