# Generated by Django 4.0.5 on 2022-07-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_remove_order_pickup_date_alter_pickup_pickup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='pickup',
            field=models.DateField(null=True, verbose_name='Pickup Date'),
        ),
    ]
