# Generated by Django 4.0.5 on 2022-07-18 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_pickup_pickup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insproduct',
            name='Prod_Price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='insproduct',
            name='Prod_stockQty',
            field=models.IntegerField(verbose_name='Stock Quantity'),
        ),
        migrations.AlterField(
            model_name='insproduct',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickupstat',
            field=models.ForeignKey(blank=True, default='Pending', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.pickupstatus'),
        ),
        migrations.AlterField(
            model_name='otcproduct',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
