# Generated by Django 4.0.5 on 2022-07-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_otcproduct_prod_stockqty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otcproduct',
            name='Prod_stockQty',
            field=models.IntegerField(verbose_name='Stock Quantity'),
        ),
    ]
