# Generated by Django 4.0.5 on 2022-07-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_otcproduct_prod_stockqty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otcproduct',
            name='Prod_Desc',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Description'),
        ),
    ]
