# Generated by Django 4.0.5 on 2022-07-18 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_otcproduct_prod_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insproduct',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='otcproduct',
            name='expiry_date',
        ),
    ]
