# Generated by Django 4.0.5 on 2022-07-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_remove_insproduct_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insproduct',
            name='expiry_date',
            field=models.DateField(null=True, verbose_name='Expiry Date'),
        ),
        migrations.AddField(
            model_name='otcproduct',
            name='expiry_date',
            field=models.DateField(null=True, verbose_name='Expiry Date'),
        ),
    ]
