# Generated by Django 4.0.5 on 2022-07-21 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_rename_pickup_orderpickup_pickup_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderpickup',
            old_name='pickup_date',
            new_name='pickup',
        ),
    ]
