# Generated by Django 4.0.5 on 2022-07-22 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_remove_order_orderitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderpickup',
            old_name='pickup',
            new_name='pickup_date',
        ),
    ]
