# Generated by Django 4.0.5 on 2022-07-24 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_rename_pickup_date_orderpickup_pickup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_pickup',
        ),
        migrations.AddField(
            model_name='orderpickup',
            name='orderitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.orderitem'),
        ),
    ]
