# Generated by Django 4.0.5 on 2022-07-24 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_remove_orderpickup_orderitem_orderpickup_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpickup',
            name='orderitem',
        ),
    ]
